version: '3.8'

services:
  inference:
    build: .
    container_name: segmentation_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./research:/app/research
    restart: always
    depends_on:
      - redis
    command: gunicorn -w 2 -t 120 -b 0.0.0.0:8000 main:app

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--slaveof", "no", "one",
      "--appendonly", "yes",
      "--save", "900", "1",
      "--auto-aof-rewrite-percentage", "100",
      "--auto-aof-rewrite-min-size", "64mb"
    ]
    volumes:
      - redis_data:/data
    restart: always

  flower:
    build: .
    container_name: flower_monitor
    working_dir: /app
    command: sh -c "PYTHONPATH=/app celery -A segmentation_tasks.celery_app flower --port=5555"
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app
      - ./research:/app/research
    depends_on:
      - redis
    restart: always

  celery_worker:
    build: .
    container_name: celery_worker
    working_dir: /app
    command: ["supervisord", "-c", "/app/supervisord.conf"]
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
      - ./research:/app/research
    depends_on:
      - redis
    restart: always


volumes:
  redis_data: